default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: localhost

development:
  <<: *default
  database: realtime_sms_notification_development

test:
  <<: *default
  database: realtime_sms_notification_test

production:
  <<: *default
  database: realtime_sms_notification_production
  #username: task_manager
  #password: <%= ENV['TASK_MANAGER_DATABASE_PASSWORD'] %>
